# Generated by Django 5.2 on 2025-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("closest_big_city", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("name", "closest_big_city")},
            },
        ),
    ]
