# Generated by Django 5.2 on 2025-04-28 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "condition",
                    models.CharField(
                        choices=[("good", "Good"), ("damaged", "Damaged")],
                        default="good",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoAirplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("country_of_origin", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=20)),
                (
                    "max_cargo_capacity",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cargo_hold_volume",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "max_range_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)]
                    ),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        related_name="cargo_airplanes", to="airport.cargo"
                    ),
                ),
            ],
        ),
    ]
