# Generated by Django 5.2 on 2025-04-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_cargo_cargoairplane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoairplane",
            name="cargos",
            field=models.ManyToManyField(
                null=True, related_name="cargo_airplanes", to="airport.cargo"
            ),
        ),
    ]
