# Generated by Django 5.2 on 2025-04-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_cargoairplane_cargos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargoairplane",
            name="cargos",
        ),
        migrations.AddField(
            model_name="cargoairplane",
            name="cargos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargo_airplanes",
                to="airport.cargo",
            ),
        ),
    ]
