# Generated by Django 5.2 on 2025-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_remove_cargoairplane_cargos_cargoairplane_cargos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargoairplane",
            name="cargos",
        ),
        migrations.AddField(
            model_name="cargoairplane",
            name="cargos",
            field=models.ManyToManyField(
                blank=True, related_name="cargo_airplanes", to="airport.cargo"
            ),
        ),
    ]
