# Generated by Django 5.2 on 2025-04-29 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_remove_cargoairplane_cargos_cargoairplane_cargos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("badge_number", models.PositiveIntegerField(unique=True)),
                (
                    "experience",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cargoairplane",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cargoairplane",
            name="pilots",
            field=models.ManyToManyField(
                blank=True, related_name="cargo_airplanes", to="airport.pilot"
            ),
        ),
    ]
