# Generated by Django 5.2 on 2025-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0008_remove_cargoairplane_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airport",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
