# Generated by Django 5.2 on 2025-05-01 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0009_alter_airport_unique_together_alter_airport_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelAirplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("country_of_origin", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=20)),
                (
                    "max_range_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)]
                    ),
                ),
                ("rows", models.PositiveIntegerField()),
                ("seats_in_row", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="airport.cargoairplane"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="airport.route"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_from",
                to="airport.airport",
            ),
        ),
    ]
