# Generated by Django 5.2 on 2025-05-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0010_travelairplane_alter_flight_airplane_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="airplane",
        ),
        migrations.AddField(
            model_name="flight",
            name="cargo_airplane",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.cargoairplane",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="travel_airplane",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.travelairplane",
            ),
        ),
    ]
