# Generated by Django 5.2 on 2025-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0012_cargoflight_travelflight_delete_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveIntegerField(),
        ),
    ]
