# Generated by Django 5.2 on 2025-05-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0013_alter_route_distance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
