# Generated by Django 5.2 on 2025-05-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0014_alter_route_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargoairplane",
            name="cargos",
        ),
        migrations.RemoveField(
            model_name="cargoflight",
            name="cargo_airplane",
        ),
        migrations.RemoveField(
            model_name="cargoflight",
            name="route",
        ),
        migrations.RemoveField(
            model_name="travelflight",
            name="travel_airplane",
        ),
        migrations.RemoveField(
            model_name="travelflight",
            name="route",
        ),
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.DeleteModel(
            name="CargoAirplane",
        ),
        migrations.DeleteModel(
            name="CargoFlight",
        ),
        migrations.DeleteModel(
            name="TravelAirplane",
        ),
        migrations.DeleteModel(
            name="TravelFlight",
        ),
    ]
