# Generated by Django 5.2 on 2025-05-01 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airport", "0015_remove_cargoairplane_cargos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelAirplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("country_of_origin", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=20)),
                (
                    "max_range_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)]
                    ),
                ),
                ("rows", models.PositiveIntegerField()),
                ("seats_in_row", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TravelFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.route"
                    ),
                ),
                (
                    "travel_airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel.travelairplane",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
