# Generated by Django 5.2 on 2025-05-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0015_remove_cargoairplane_cargos_and_more"),
        ("travel", "0002_travelorder_travelticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelflight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_flights",
                to="airport.route",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="travelticket",
            unique_together={("row", "seat", "travel_flight")},
        ),
    ]
