# Generated by Django 5.2 on 2025-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0015_remove_cargoairplane_cargos_and_more"),
        ("travel", "0003_alter_travelflight_route_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelflight",
            name="pilots",
            field=models.ManyToManyField(
                related_name="travel_flights", to="airport.pilot"
            ),
        ),
    ]
