# Generated by Django 5.2 on 2025-05-01 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airport", "0015_remove_cargoairplane_cargos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "condition",
                    models.CharField(
                        choices=[("good", "Good"), ("damaged", "Damaged")],
                        default="good",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoAirplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("country_of_origin", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=20)),
                (
                    "max_range_km",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)]
                    ),
                ),
                (
                    "max_cargo_capacity",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cargo_hold_volume",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        blank=True, related_name="cargo_airplanes", to="cargo.cargo"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CargoFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "cargo_airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cargo.cargoairplane",
                    ),
                ),
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="airport.route"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
