# Generated by Django 5.2 on 2025-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0003_alter_cargo_volume_alter_cargo_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="is_delivered",
        ),
    ]
