# Generated by Django 5.2 on 2025-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0004_remove_cargo_condition_remove_cargo_is_delivered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargoairplane",
            name="cargos",
        ),
    ]
