# Generated by Django 5.2 on 2025-05-03 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0015_remove_cargoairplane_cargos_and_more"),
        ("cargo", "0006_cargoorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoflight",
            name="pilots",
            field=models.ManyToManyField(
                related_name="cargo_flights", to="airport.pilot"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="volume",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
