# Generated by Django 5.2 on 2025-05-03 12:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0007_cargoflight_pilots_alter_cargo_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="volume",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
