# Generated by Django 5.2 on 2025-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0010_alter_cargo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoairplane",
            name="cargo_hold_volume",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cargoairplane",
            name="max_cargo_capacity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
