# Generated by Django 5.2 on 2025-05-04 12:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0011_alter_cargoairplane_cargo_hold_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoairplane",
            name="cargo_hold_volume",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="cargoairplane",
            name="max_cargo_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
